# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_beta_psi_mu2 <- function(Y, X, beta, psi, mu2, n) {
    .Call('_MeRIPtools_gradient_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, n)
}

log_factorial <- function(Y) {
    .Call('_MeRIPtools_log_factorial', PACKAGE = 'MeRIPtools', Y)
}

log_factorial_calculated <- function(N) {
    .Call('_MeRIPtools_log_factorial_calculated', PACKAGE = 'MeRIPtools', N)
}

LogLikelihood_beta_psi_mu2 <- function(Y, X, beta, psi, mu2, n, sum_log_factorial_Y) {
    .Call('_MeRIPtools_LogLikelihood_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, n, sum_log_factorial_Y)
}

select_stepsize_for_beta <- function(Y, X, gra_beta, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down) {
    .Call('_MeRIPtools_select_stepsize_for_beta', PACKAGE = 'MeRIPtools', Y, X, gra_beta, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down)
}

select_stepsize_for_psi <- function(Y, X, gra_psi, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down, psi_cutoff) {
    .Call('_MeRIPtools_select_stepsize_for_psi', PACKAGE = 'MeRIPtools', Y, X, gra_psi, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down, psi_cutoff)
}

select_stepsize_for_mu2 <- function(Y, X, gra_mu2, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down) {
    .Call('_MeRIPtools_select_stepsize_for_mu2', PACKAGE = 'MeRIPtools', Y, X, gra_mu2, ll, beta, psi, mu2, n, gamma, sum_log_factorial_Y, down)
}

gradient_descent_beta_psi_mu2 <- function(Y, X, beta, psi, mu2, gamma, steps, sum_log_factorial_Y, down, psi_cutoff) {
    .Call('_MeRIPtools_gradient_descent_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, gamma, steps, sum_log_factorial_Y, down, psi_cutoff)
}

gradient_descent_alt <- function(Y, X, psi, mu2, gamma, steps, sum_log_factorial_Y, down, psi_cutoff) {
    .Call('_MeRIPtools_gradient_descent_alt', PACKAGE = 'MeRIPtools', Y, X, psi, mu2, gamma, steps, sum_log_factorial_Y, down, psi_cutoff)
}

PoissionGamma <- function(Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff) {
    .Call('_MeRIPtools_PoissionGamma', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff)
}

Fisher_information_one_beta <- function(Y, X, beta, psi, mu2, n) {
    .Call('_MeRIPtools_Fisher_information_one_beta', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, n)
}

PoissionGamma_FISHER <- function(Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff) {
    .Call('_MeRIPtools_PoissionGamma_FISHER', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff)
}

gradient_and_LogLikelihood_for_individual_sample <- function(Y, W, V, WY, WWY, W3Y, W4Y, VY, VVY, V3Y, V4Y, WW, W3, W4, VV, V3, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, n, sum_log_factorial_Y) {
    .Call('_MeRIPtools_gradient_and_LogLikelihood_for_individual_sample', PACKAGE = 'MeRIPtools', Y, W, V, WY, WWY, W3Y, W4Y, VY, VVY, V3Y, V4Y, WW, W3, W4, VV, V3, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, n, sum_log_factorial_Y)
}

LogLikelihood_for_individual_sample <- function(Y, W, V, WW, VV, W3, V3, W4, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, n, sum_log_factorial_Y) {
    .Call('_MeRIPtools_LogLikelihood_for_individual_sample', PACKAGE = 'MeRIPtools', Y, W, V, WW, VV, W3, V3, W4, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, n, sum_log_factorial_Y)
}

select_stepsize_for_a_parameter <- function(Y, W, V, WW, VV, W3, V3, W4, V4, ll, sum_log_factorial_Y, gradient, parameters, ind, gamma, n, down) {
    .Call('_MeRIPtools_select_stepsize_for_a_parameter', PACKAGE = 'MeRIPtools', Y, W, V, WW, VV, W3, V3, W4, V4, ll, sum_log_factorial_Y, gradient, parameters, ind, gamma, n, down)
}

gradient_descent_for_individual_sample <- function(Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, gamma, steps, down) {
    .Call('_MeRIPtools_gradient_descent_for_individual_sample', PACKAGE = 'MeRIPtools', Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, gamma, steps, down)
}

coordinate_descent_for_individual_sample <- function(Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, gamma, steps, down) {
    .Call('_MeRIPtools_coordinate_descent_for_individual_sample', PACKAGE = 'MeRIPtools', Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, gamma, steps, down)
}

gradient_multiple_beta_psi_mu2 <- function(Y, X, Xbeta, psi, mu2, n, k) {
    .Call('_MeRIPtools_gradient_multiple_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, X, Xbeta, psi, mu2, n, k)
}

LogLikelihood_multiple_beta_psi_mu2 <- function(Y, Xbeta, psi, mu2, n, sum_log_factorial_Y) {
    .Call('_MeRIPtools_LogLikelihood_multiple_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, Xbeta, psi, mu2, n, sum_log_factorial_Y)
}

select_stepsize_for_multiple_beta <- function(Y, X, betas, Xbeta, ind, m_gra_beta, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down) {
    .Call('_MeRIPtools_select_stepsize_for_multiple_beta', PACKAGE = 'MeRIPtools', Y, X, betas, Xbeta, ind, m_gra_beta, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down)
}

select_stepsize_for_psi_with_multiple_beta <- function(Y, Xbeta, gra_psi, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down, psi_cutoff) {
    .Call('_MeRIPtools_select_stepsize_for_psi_with_multiple_beta', PACKAGE = 'MeRIPtools', Y, Xbeta, gra_psi, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down, psi_cutoff)
}

select_stepsize_for_mu2_with_multiple_beta <- function(Y, Xbeta, gra_mu2, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down) {
    .Call('_MeRIPtools_select_stepsize_for_mu2_with_multiple_beta', PACKAGE = 'MeRIPtools', Y, Xbeta, gra_mu2, ll, psi, mu2, n, gamma, sum_log_factorial_Y, down)
}

gradient_descent_multiple_beta_psi_mu2 <- function(Y, X, beta, psi, mu2, gamma, steps, sum_log_factorial_Y, n, k, down, psi_cutoff) {
    .Call('_MeRIPtools_gradient_descent_multiple_beta_psi_mu2', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, gamma, steps, sum_log_factorial_Y, n, k, down, psi_cutoff)
}

Fisher_information <- function(Y, X, Xbeta, psi, mu2, n, k) {
    .Call('_MeRIPtools_Fisher_information', PACKAGE = 'MeRIPtools', Y, X, Xbeta, psi, mu2, n, k)
}

PoissionGamma_multiple_beta <- function(Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff) {
    .Call('_MeRIPtools_PoissionGamma_multiple_beta', PACKAGE = 'MeRIPtools', Y, X, beta, psi, mu2, gamma, steps, down, psi_cutoff)
}

